"""Make user_id nullable in transactions

Revision ID: 207eda0fe227
Revises: 8edd1a5fc93b
Create Date: 2026-08-06 16:58:27.519945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207eda0fe227'
down_revision = '8edd1a5fc93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
